# Generated by Django 4.1.5 on 2023-01-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('region_name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
