# Generated by Django 4.1.5 on 2023-01-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['name', '-published_at'], 'verbose_name': 'Вакансии', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название вакансии'),
        ),
    ]
